### ISSUE TITLE
Code coverage support for Emulator

### ISSUE THREAD

**Issue by turbolent** [onflow/developer-grants#113]
# Grant category

Please select one or more of:

- [x]  Open source maintenance
- [x]  Developer tools / services
- [ ]  Educational material

# Description

## Problem statement

The Flow Emulator is the developer tool for the Flow blockchain which allows developers to develop Cadence smart contracts.

Testing is an essential part of the development workflow. 

Developers want to measure how well their tests cover their contracts. 

The Flow Emulator should provide code coverage functionality.

The Cadence core contributors added support for code coverage support a long time ago, but have not exposed this functionality to developers yet.

## Solution requirements

The solution should expand on the current state of the code coverage functionality of Cadence and allow and add support for it to the Flow emulator. 

## Submission requirements

- Integration tests

**Comment by m-Peter** [comment]
Hi @turbolent and @chrisackermann,

I have had a look at this grant, and it is quite interesting. Testing is indeed an essential part of the development workflow and code coverage is an important metric that can help engineers view what percentage of all the possible code paths have been exercised!

> The Cadence core contributors added support for code coverage support a long time ago, but have not exposed this functionality to developers yet.

The above statement prompted me to search the relevant repositories and to map out what is already available and what needs to be added. I wanted to get a high-level overview of how things could possibly be wired together.

Here's what I found on the `Cadence` repository:

- [CoverageReportingEnabled](https://github.com/onflow/cadence/blob/c1db9ec13ae369db0a0c1d7f90f63745b45187ed/runtime/config.go#L34-L35) This is the relevant config property which denotes whether coverage reporting is enabled or not for the runtime.
- [Usage of the config property](https://github.com/onflow/cadence/blob/8d84bebd6fc14302450803ba033fc256d5ac1c39/runtime/coverage_test.go#L37-L39) to create a Cadence interpeter runtime with coverage reporting enabled. (for testing purposes)
- [Using a CoverageReport](https://github.com/onflow/cadence/blob/8d84bebd6fc14302450803ba033fc256d5ac1c39/runtime/coverage_test.go#L74-L87) object in a [execution context](https://github.com/onflow/flow-go/tree/master/fvm#contexts), in order to calculate the [coverage](https://github.com/onflow/cadence/blob/8d84bebd6fc14302450803ba033fc256d5ac1c39/runtime/coverage_test.go#L97-L115) for a script execution.
- [CoverageReport](https://github.com/onflow/cadence/blob/c1db9ec13ae369db0a0c1d7f90f63745b45187ed/runtime/coverage.go) source code.

Regarding the wiring with the `flow-emulator` repository:

- A new [configuration flag](https://github.com/onflow/flow-emulator/blob/master/cmd/emulator/start/start.go#L42) would be needed, such as:

```go
CoverageReportEnabled   bool    `default:"false" flag:"coverage-report" info:"Enable coverage reporting"`
```

- Proper [FVM configuration](https://github.com/onflow/flow-emulator/blob/master/blockchain.go#L407-L417) will also be needed, such as:

```go
vm := fvm.NewVirtualMachine()

fvmOptions := []fvm.Option{
	// ... all other options,
	fvm.WithCoverageReporting(conf.CoverageReportEnabled)
}

// Possibly this is where we need to inject the CoverageReport object.
if conf.CoverageReportEnabled {
	fvmOptions = append(fvmOptions, fvm.WithCoverageReport(fvm.NewCoverageReport()))
}
```

At a high-level, the developers would be running scripts and transactions (possibly from a test suite) to a `flow-emulator` process/object that is properly configured for coverage reporting, which would in turn result in a coverage report about the code pieces that were exercised during the test suite run.

This is just my understanding after scratching the surface for about a day :sweat_smile:. If this makes any sense to you, I would be interested in proceeding further, and with the squad at @Build-Squad convert it to a proper grant proposal :pray:.

**Comment by turbolent** [comment]
@m-Peter Great to see you are interested! 

Thank you for looking into the code and summarizing the current state, your write-up reflects it well 👌 

Basically, the Cadence `interpreter` and `runtime` packages have some support for collecting a coverage report, and the next step would be to allow it to be enabled in the FVM, then the Emulator, and finally in the testing framework (https://github.com/onflow/cadence-tools/tree/master/test), so that ultimately it can be enabled by the user/developer in the CLI when running a test through a command line option, e.g. `flow test --coverage coverage.txt tests.cdc`.

The coverage report should probably be exportable to a widely supported format, see e.g. https://docs.codecov.com/docs/supported-report-formats for an overview.

cc @SupunS

**Comment by turbolent** [comment]
@m-Peter Please go ahead with submitting a proper grant proposal. We are looking forward to reviewing it! :-)

**Comment by m-Peter** [comment]
Thank you @turbolent, for your reply & detailed feedback :pray: It does make things more clear, for the desired deliverable :rocket: 

We'll proceed with writing up the grant proposal, and explore more of the related codebase in the meanwhile :runner:

**Comment by bluesign** [comment]
I would suggest few things: 

- One line can have multiple statements, it would be nice to add support for that. ( nil coalescence for example ) 
- emulator has a management REST API; managing code coverage via that would be very nice for other testing frameworks to use code coverage.

**Comment by m-Peter** [comment]
> @m-Peter Please go ahead with submitting a proper grant proposal. We are looking forward to reviewing it! :-)

You can find it here @turbolent :pray: 



> I would suggest few things:
> 
>     * One line can have multiple statements, it would be nice to add support for that. ( nil coalescence for example )
> 
>     * emulator has a management REST API; managing code coverage via that would be very nice for other testing frameworks to use code coverage.

Both points are quite valid, I will have a quick look at the management REST API, as I wasn't aware of it!

**Comment by m-Peter** [comment]
@turbolent @SupunS You can find a PoC in this [gist](https://gist.github.com/m-Peter/391852ded7a8b1ee602d84ab8728a20f). I was toying with the codebase locally, to develop some intuition around the problem :pray: One rather old, but still interesting [read](https://go.dev/blog/cover) regarding code coverage, from the prolific `Rob Pike` :bow:

**Comment by turbolent** [comment]
@m-Peter nice!

The article has a great section, "Basic blocks", which describes the limitation of not tracking individual expressions. Cadence also is inexact in that way and only tracks statements. I think that is fair for the first iteration / MVP, and can be extended in the future.
