### ISSUE TITLE
Flowser: Integrate into the Flow CLI

### ISSUE THREAD

**Issue by alxflw** [onflow/developer-grants#13]
mentioned by @sideninja

**Comment by bluesign** [comment]
@sideninja will it be TUI ? This can be really nice addition to CLI

**Comment by sideninja** [comment]
> @sideninja will it be TUI ? This can be really nice addition to CLI
@bluesign Yes!

**Comment by sideninja** [comment]
Pinging flowser team to start a plan for this action 
cc @bartolomej @monikaxh

**Comment by alxflw** [comment]
ideally, the team would submit a grant application with milestones 🙏

**Comment by monikaxh** [comment]
> @sideninja will it be TUI ? This can be really nice addition to CLI

Do you maybe mean GUI? In that case of course


> ideally, the team would submit a grant application with milestones 🙏

Sure @alxflw! We are preparing it and we will share it shortly!

**Comment by monikaxh** [comment]
Hi @alxflw 

The main idea is to integrate flow-cli and to launch a new Flowser desktop app (currently a web app). Now, the UX of Flowser is not optimal because the user needs to have another program (Docker) to launch it. Non-docker users would find this frustrating. 

If we integrate flow-cli and launch a new Flowser desktop app the UX (ease of use, execution time, resource usage,..) would be optimized, and support of the newest CLI versions would enable new functionalities in Flowser and give us unlimited possibilities for developing new features. For example: to integrate snapshot management into Flowser.

With @bartolomej we've prepared the document with more details and a timeline. Could you please let us know, where we can send this document?

**Comment by monikaxh** [comment]
<h1>Grant application &amp; milestones</h1>
<h2><strong>Grant category</strong></h2>
<p>OpenSource maintenance</p>
<h2>Description</h2>
<p>Create a standalone Flowser application that can be simply installed and also launched
within the Flow CLI.</p>
<h2>Problem statement</h2>
<p>Even though a Flowser was built to be easy to use and developer-friendly the installation process requires multiple steps and tools to be pre-installed which in the end hurts the UX. We want to make Flowser as accessible as possible and part of that would be to wrap it up in a standalone application that doesn’t require other dependencies and it works with a single click. The wish for this improvement was also confirmed by our community on GitHub as seen here: <a href="https://github.com/onflowser/flowser/discussions"><a href="https://github.com/onflowser/flowser/discussions">https://github.com/onflowser/flowser/discussions</a></a></p>
<ul>
<li>Currently, in order to install the Flowser you need to pre-install:
<ul>
<li>NodeJS environment</li>
<li>Postgres database</li>
<li>Docker</li>
</ul>
</li>
</ul>
<p>Besides the technical difficulties, the current version comes with a cost of higher CPU
and memory usage as well as isolation of the Flow CLI which is contained in a docker
instead of using the one user has already installed on their system.</p>
<h2>Proposed solution</h2>
<p>Our proposed solution consists of multiple steps. First, we would have to make sure Flowser is updated with the latest versions of the CLI and Emulator, then we would work on removing the dependencies mentioned above. Postgres database would be swapped with in-memory storage that would have an abstract API and hideaway technicalities of data persistence. Since the Flowser application would be launched by the CLI after we complete all the changes we can remove the CLI as a dependency too and use the one that launched the Flowser in the first place. We would follow by making sure the Flowser can be launched in a platform-independent which would allow us to wrap it in an Electron environment. Electron is a framework for creating native applications from web applications. Last but not least all of the above-mentioned actions would be accompanied by changes in the UI design, improvements in the UX, and support for any new UI components.</p>
<h2>Impact</h2>
<ul>
<li>The user experience would be much more convenient and pleasant when working with the graphical user interface.</li>
<li>Flowser would be more accessible to more developers.</li>
<li>Flowser UX (UI, ease of use, execution time, resource usage,..) would be significantly improved</li>
<li>Support of the newest CLI versions would enable new functionalities in Flowser and give us unlimited possibilities for developing new features in the future.</li>
</ul>
<h2>Timeline</h2>


Milestone | Deliverables | Timeline | Risks | FLOW requested
-- | -- | -- | -- | --
1 - Database migration | Migration to a platform-independent SQL database interface. Solve a few related issues along the way, such as <a href="https://github.com/onflowser/flowser/issues/13">data persistence issues</a> and the lack of <a href="https://github.com/onflowser/flowser/issues/6">error recovery mechanism</a>. | 2 weeks | - | 1200 |  
2 - Flowser architecture changes | Platform independent architecture to support Electron (or any other) environment. | 1 week | - | 600 | 
3 - Migration to the newest version of flow-cli and emulator | With the migration to the newest version of flow-cli we will support the newly added flow-cli functionalities and we will integrate Snapshot management into Flowser. | 3 weeks | - | 1800 | 
4 - Desktop app | Standalone application with electron support. | ~ 1 month | - | 3000 |
5 - Maintenance, support & PR | We will ensure maintenance and support for emulator and flow-cli updates. Public release and marketing will be done together with engaging our community on all of our channels: Twitter, Discord, and blog post. | 3 months | - | 3000 |  
New design and GUI improvements | The current design of the Flowser tool needs to be modified and redesigned for a standalone application and for smaller window sizes as well. An additional new design needs to be created, to support all the new functionalities, that will be available in the Flowser desktop app. We will also improve the GUI with a <a href="https://github.com/onflowser/flowser/discussions/82">SubNavigation</a> redesign. We will include global statistics on the left side of the search component, to give the user more information. These deliverables will be ongoing during milestones 1-3. This is how will we ensure, that the design will be ready for the start of milestone 4. | ~ 1 month | - | 3000 |


<h2>Team</h2>


Github | Name | Role | Bio | E-mail
-- | -- | -- | -- | --
@bartolomej | Bartolomej Kozorog | Full stack developer | Passionate developer and CS student. Currently building Flowser and part-time working at various tech companies. | bartolomej.kozorog@gmail.com
@monikaxh | Monika Hriberšek | UX/UI Design + Graphic design | Proprietor @ Monikart; UX/UI Designer @ Flowser since Sep 2021; Designing: mobile apps, websites, social media content, NFTs. Additional experience: Product Manager @ Renault&Nissan Financing (~ 4y). | monika.hribersek@gmail.com
@jakic12 | Jakob Drusany | Full stack developer | Computer science and maths student. Developing Flowser and many other personal projects. | drusany.jakob@gmail.com

**Comment by monikaxh** [comment]
cc: @alxflw @bluesign @sideninja @bartolomej

**Comment by alxflw** [comment]
thanks @monikaxh! do you mind creating a new GH issue for this so we have the wishlist item and the application independently of each other? 🙏

**Comment by monikaxh** [comment]
Sure @alxflw! We have now created a new <a href="[url](https://github.com/onflow/developer-grants/issues/27)">issue</a> 🎉

**Comment by alxflw** [comment]
grant was accepted, closing this wishlist item
