### ISSUE TITLE
.find: Show NFTs owned by a user

### ISSUE THREAD

**Issue by alxflw** [onflow/developer-grants#14]
Show NFTs a user owns by using the Alchemy API

mentioned by @albeethekid

**Comment by bjartek** [comment]
# Proposal to Dapper labs for the development of a details page for created NFT’s on the Flow Blockchain.

## Public detail page
If you want to .find information about an NFT #OnFlow right now you have some options. 
1. The origin site of that NFT
2. A Block explorer like flowscan/flow-view-source
3. View the item in BloctoApp/Lilico. If you use that wallet and if the NFT is supported

Many origin sites mix off chain data in their display and it is hard for a user to know if an asset they have purchased has truly been minted. 
A block explorer is a technical tool for tech savvy users that will give them a detailed overview of what is going on in a language that is not comfortable to many people. 
Displaying NFTs inside your own wallet has some merit, but what if others want to verify what you have/own?
For a normal user there are no good options for independent verification and display of an NFT. 
This grant aims to make such a page that will have a content addressable URL that is easy to remember and link.
The url would be something like:
find.xyz/0x886f3aeaf848c535/Flovatar/95
find.xyz/_address or find name_/<nft alias from Alchemy/nft registry>/<id>

## NFT .find page
At .find each NFT will have its own page that can be reached in a content addressable/shareable way. No login will be required and no .find name is needed. Although the link would be prettier/easier to remember if you have a .find name. 
The page will show information about this NFT from as many sources as possible and package this up into a "normie" readable way. 

### Information displayed:
 - Any known View that is exposed from this resource using the Metadata Standard will be displayed 
 - Any not-known view will be shown in an expandable way as pure JSON
- Any scrapable history of that NFT.

### Verification:
.find will try to judge the authenticity and strength of the NFT and the origin project it comes from using
 - number of transactions
 - age
 - flowverse metrics
 - other factors as they become clearer

### Fetching information:
We will try to fetch the information using the onChain NFT/Alchemy registry
We will fall back to alchemy API for TopShot and some assets that needs to be enriched. Or use the graphql api to fetch those.

Use flowgraph to show NFT purchase history for this NFT

### Integrations:
.find will strive to integrate as many other service-level solutions #OnFlow as possible. At this moment these include
 
- allow sending this NFT as a gift to another user: this feature will let the user know if there are royalties attached to the NFT and prompt the user to compensate the royalty holder if the user wants to. 
 - schwap.io: create a schwap with this item in it
 - flowty.io:  create a loan with this NFT as collateral
 - display if this NFT is listed in flowty
 - allow listing the NFT for sale/auction at the .find market
 - ist all known marketplaces that sell this NFT, for blocto/rarible it is very hard to know where it is listed because of the nature of NFTStorefront

## Value Proposition

In our eyes this offers a huge benefit to the flow ecosystem. There will be a place where everybody can view all the data about an NFT that is stored #OnChain and verify its authenticity. The web3 space on ETH is haunted by scams and this is a tool that could inform users in a simple and trusted way to help avoid that.

We are committed to develop tools and feature sets that will enable and equip end users to make informed decisions and improve user experience across all projects that engage. This is the first of many such proposals in our journey.
For us to be able to achieve this in a timely manner, we would ask for $20,000 in compensation and assurance that projects will be requested to engage with find to ensure correct display of the NFT.

Compensation explained:
 - Back end services:
 - Create the scripts needed to display the information
 - Compare and utilise this with the alchemy API to ensure non duplication of data
 - Integrate with Graphql API
 
Front End services:
 - Develop an Air gapped collection page with NFT detail page that displays the information discussed above.
 - Ensure this is content addressable and is rich with information.

Support:
 - Provide light touch support to projects wanting to be part of this proposal.

**Comment by bjartek** [comment]
Sure thing.

**Comment by alxflw** [comment]
accepted grant, thanks!
