### ISSUE TITLE
FCL example for backend usage.

### ISSUE THREAD

**Issue by tyllenb** [onflow/developer-grants#29]
# <Project name>
FCL Example for backend Usage. Signing and Authorizing
# Grant category

Please select one or more of:

- [ ] OpenSource maintenance
- [ ] Developer service
- [ ] Product bounty
- [x] Educational material

# Description
Right now there isn't too much documentation around on how to integrate FCL with the backend and how to use it for signing transactions on the front end. If someone could figure out how to create an example App or resource that helps do this for developers it would be a big win for the Flow Ecosystem.
## Problem statement

Target audience
- Developers building on Flow

Evidence for the need
- Speaking to new developers that are onboarding that don't really have an idea on how this works.

## Solution requirements
An app that integrates backend signing with the front end. Should show developers ideally how to do the following. More examples would also be beneficial.

- Create Collections
- Mint NFT's
- Transfer NFT's

**Comment by Aliserag** [comment]
We appreciate your proposal and taking the time to fill it out. Given the time since this has been submitted I'm closing this down, please reach out to me if you'd like to share what you're working on now and explore potential opportunities [ali.serag@flowfoundation.org](mailto:ali.serag@flowfoundation.org).
